# Generated by Django 5.2.8 on 2025-12-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_tenantsubscription_stripe_customer_id_and_more'),
        ('tenants', '0006_tenant_stripe_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantsubscription',
            old_name='stripe_customer_id',
            new_name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='tenantsubscription',
            name='stripe_payment_method_id',
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='api_rows_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
