# Generated by Django 5.2.8 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='cad', max_length=3),
        ),
    ]
