# Generated by Django 5.2.8 on 2025-12-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_groups',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='max_groups',
            field=models.IntegerField(default=5),
        ),
    ]
