# Generated by Django 5.2.8 on 2025-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_tenantsubscription_auto_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='max_api_rows',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='max_dashboards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='max_datasets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='max_users',
            field=models.IntegerField(default=0),
        ),
    ]
