# Generated by Django 5.2.8 on 2025-12-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_tenantsubscription_max_api_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
