# Generated by Django 5.2.8 on 2025-12-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_stripe_customer_id_tenantsubscription_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
