# Generated by Django 5.2.8 on 2025-12-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_chart_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartjoin',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='dashboards.chart'),
        ),
    ]
