# Generated by Django 5.2.8 on 2025-12-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_apidatasource_tenant_chart_tenant_chartjoin_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='logic_expression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='logic_rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='aggregation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboards.dataset'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='x_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='y_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
