# Generated by Django 5.2.8 on 2025-12-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_chart_filters_chart_logic_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidatasource',
            name='jwt_audience',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='jwt_issuer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='jwt_secret',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='jwt_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='jwt_ttl_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='api_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('API_KEY_HEADER', 'API Key (Header)'), ('BEARER', 'Bearer Token'), ('API_KEY_QUERY', 'API Key (Query Param)'), ('JWT_HS256', 'JWT (HS256)')], default='NONE', max_length=32),
        ),
    ]
