# Generated by Django 5.2.8 on 2025-12-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_apidatasource_jwt_audience_apidatasource_jwt_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
