# Generated by Django 5.2.8 on 2025-12-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_group_deleted_at_group_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidatasource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
