# Generated by Django 5.2.8 on 2025-12-24 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_dataset_is_deleted_alter_dataset_endpoint'),
        ('tenants', '0007_tenantuser_default_payment_method_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apidatasource',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='apidatasource',
            name='api_key_header',
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='api_key_name',
            field=models.CharField(default='Authorization', help_text='Header name or query param name', max_length=255),
        ),
        migrations.AddField(
            model_name='apidatasource',
            name='bearer_token',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('API_KEY_HEADER', 'API Key (Header)'), ('API_KEY_QUERY', 'API Key (Query Param)'), ('BEARER', 'Bearer Token'), ('JWT_HS256', 'JWT (HS256)')], default='NONE', max_length=32),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='jwt_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='jwt_issuer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apidatasource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_sources', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='apidatasource',
            index=models.Index(fields=['tenant', 'is_deleted'], name='dashboards__tenant__be5d33_idx'),
        ),
    ]
