# Generated by Django 5.2.8 on 2025-12-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='default_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
