# Generated by Django 5.2.8 on 2025-12-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_default_payment_method_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
