# Generated by Django 5.2.8 on 2025-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
