# Generated by Django 5.2.8 on 2025-12-02 11:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('NONE', 'None'), ('API_KEY_HEADER', 'API Key (Header)'), ('BEARER', 'Bearer Token'), ('API_KEY_QUERY', 'API Key (Query Param)')], default='NONE', max_length=32)),
                ('api_key', models.CharField(blank=True, help_text='Write-only; used for requests', max_length=1024)),
                ('api_key_header', models.CharField(default='Authorization', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('min', 'Min'), ('max', 'Max'), ('count', 'Count'), ('none', 'None')], default='none', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie'), ('kpi', 'KPI'), ('table', 'Table')], default='bar', max_length=32)),
                ('x_field', models.CharField(blank=True, max_length=255)),
                ('y_field', models.CharField(blank=True, max_length=255)),
                ('excel_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.chart')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_charts', to='dashboards.dashboard')),
            ],
            options={
                'unique_together': {('dashboard', 'chart')},
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='charts',
            field=models.ManyToManyField(related_name='dashboards', through='dashboards.DashboardChart', to='dashboards.chart'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('endpoint', models.CharField(help_text='Path appended to base_url, e.g. /v1/data', max_length=1024)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='dashboards.apidatasource')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_field', models.CharField(max_length=255)),
                ('right_field', models.CharField(max_length=255)),
                ('on_condition', models.CharField(blank=True, max_length=512, null=True)),
                ('left_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_joins', to='dashboards.dataset')),
                ('right_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_joins', to='dashboards.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dashboards.dataset'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dashboards', models.ManyToManyField(blank=True, related_name='groups', to='dashboards.dashboard')),
                ('users', models.ManyToManyField(blank=True, related_name='dashboard_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
