# Generated by Django 5.2.8 on 2025-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartjoin',
            name='type',
            field=models.CharField(choices=[('inner', 'Inner'), ('left', 'Left'), ('right', 'Right')], default='inner', max_length=10),
        ),
    ]
