# Generated by Django 5.2.8 on 2025-12-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_chartjoin_chart'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidatasource',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apidatasource_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chart',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='chartjoin',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chartjoin_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dashboardchart',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboardchart_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='tenants.tenant'),
        ),
    ]
